version: '3.8'

services:
  ollama-server:
    container_name: ollama-server
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/dri:/dev/dri
    environment:
      - INTEL_GPU_DEVICE=/dev/dri
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
    volumes:
      - ollama:/app/backend/data
    networks:
      - ollama-net

volumes:
  ollama:

networks:
  ollama-net:
    driver: bridge
